import React from 'react';
import {Pressable,View} from 'react-native';
import {Image} from 'expo-image';
import {LinearGradient} from 'expo-linear-gradient';
import {useTheme} from '../lib/theme';
import {useStore} from '../lib/store';
import {useUI} from '../lib/navigation';
import {imageSource,money,photos} from '../lib/data';
import {Avatar,Button,Card,Icon,Row,T} from './ui';
export default function DiscoveryPanel(){const{c}=useTheme();const s=useStore();const ui=useUI();return <View style={{width:282,gap:18}}>
 <Card style={{padding:17}}><Row style={{justifyContent:'space-between'}}><T size={14} weight="bold">Find your neighborhood</T><Icon name="location-outline" size={17} color={c.primary}/></Row><T size={10} color={c.muted} style={{marginTop:4,marginBottom:15}}>Good places, a little closer to you.</T><Row style={{gap:10}}>{[{city:'Bhopal',image:photos.bhopal,label:'The city of lakes'},{city:'Indore',image:photos.indore,label:'Room to grow'}].map(n=><Pressable key={n.city} onPress={()=>{ui.setQuery(n.city);ui.navigate('Explore')}} style={{flex:1,height:137,borderRadius:9,overflow:'hidden'}}><Image source={n.image} style={{width:'100%',height:'100%'}} contentFit="cover"/><LinearGradient colors={['transparent','#13213ACF']} style={{position:'absolute',inset:0} as any}/><View style={{position:'absolute',bottom:11,left:11,right:5}}><T size={15} color="#fff" weight="bold">{n.city}</T><T size={8} color="#FFFFFFC9">{s.properties.filter(p=>p.city===n.city).length} places to discover</T></View></Pressable>)}</Row><Pressable onPress={()=>{ui.setQuery('');ui.navigate('Explore')}} style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingTop:15}}><T size={10} weight="bold" color={c.primary}>Explore all locations</T><Icon name="arrow-forward" size={14} color={c.primary}/></Pressable></Card>
 <Card style={{padding:17}}><Row style={{justifyContent:'space-between',marginBottom:16}}><T size={14} weight="bold">Worth a closer look</T><Icon name="sparkles-outline" color={c.primary} size={17}/></Row>{s.properties.filter(p=>p.id!=='pavera-1001'&&['For Sale','For Rent'].includes(p.status)).slice(0,3).map((p,i)=><Pressable key={p.id} onPress={()=>{s.viewProperty(p.id);ui.open('details',p.id)}} style={{flexDirection:'row',gap:11,marginBottom:i===2?0:16}}><Image source={imageSource(p.photos[0])} style={{width:69,height:66,borderRadius:8}} contentFit="cover"/><View style={{flex:1,justifyContent:'center'}}><T size={11} weight="bold" numberOfLines={1}>{p.beds} BHK {p.type}</T><Row style={{gap:3,marginTop:3}}><Icon name="location-outline" size={10}/><T size={9} color={c.muted}>{p.locality}, {p.city}</T></Row><T size={12} weight="extra" color={c.navy} style={{marginTop:3}}>{money(p.price,true)}{p.purpose==='Rent'&&<T size={8} color={c.muted}> / mo</T>}</T></View><Icon name="chevron-forward-outline" size={13}/></Pressable>)}</Card>
 <Card style={{padding:17}}><T size={14} weight="bold">People who know places</T><T size={10} color={c.muted} style={{marginTop:4,marginBottom:15}}>A local perspective goes a long way.</T>{[{name:'Priya Sharma',photo:photos.priya,area:'Bhopal',id:'demo-priya'},{name:'Rahul Verma',photo:photos.rahul,area:'Indore',id:'demo-rahul'}].map((a,i)=><Row key={a.name} style={{gap:9,marginBottom:i===0?14:0}}><Pressable onPress={()=>ui.open('seller',a.id)}><Avatar source={a.photo} size={35}/></Pressable><View style={{flex:1}}><Pressable onPress={()=>ui.open('seller',a.id)}><T size={10} weight="bold">{a.name}</T></Pressable><T size={9} color={c.muted}>Property advisor · {a.area}</T></View><Pressable accessibilityLabel={s.following.includes(a.name)?`Unfollow ${a.name}`:`Follow ${a.name}`} onPress={()=>s.follow(a.name)} style={{width:28,height:28,borderRadius:7,borderWidth:1,borderColor:c.line,alignItems:'center',justifyContent:'center'}}><Icon name={s.following.includes(a.name)?'checkmark':'add'} size={16} color={c.primary}/></Pressable></Row>)}</Card>
 <View style={{paddingHorizontal:8,gap:11}}><Row style={{flexWrap:'wrap',gap:12}}>{['About','Privacy','Terms','Help & support'].map(a=><Pressable key={a} onPress={()=>ui.open('info',a)}><T size={9} color={c.muted}>{a}</T></Pressable>)}</Row><Row style={{gap:6}}><Image source={require('../assets/images/pavera-logo.png')} style={{width:15,height:15}}/><T size={10} weight="extra" color={c.muted}>pavera</T><T size={9} color={c.muted}>© 2026 · A place for possibility.</T></Row>{s.demo&&<Row style={{gap:5}}><View style={{width:5,height:5,borderRadius:4,backgroundColor:'#B19A69'}}/><T size={8} color={c.muted}>DEMO WORKSPACE · SAMPLE LISTINGS</T></Row>}</View>
 </View>}
