import React,{useState} from 'react';
import {Pressable,View} from 'react-native';
import {Image} from 'expo-image';
import {Property} from '../lib/types';
import {imageSource,money} from '../lib/data';
import {useTheme} from '../lib/theme';
import {useStore} from '../lib/store';
import {useUI} from '../lib/navigation';
import {Avatar,Badge,Button,Card,Icon,IconButton,Row,T} from './ui';
export default function PropertyCard({property:p,compact=false}:{property:Property;compact?:boolean}){
 const{c}=useTheme();const s=useStore();const ui=useUI();const[imageIndex,setImageIndex]=useState(0);const saved=s.saved.includes(p.id);const liked=s.liked.includes(p.id);const comments=s.comments.filter(x=>x.propertyId===p.id).length;
 const details=()=>{s.viewProperty(p.id);ui.open('details',p.id)};
 if(compact)return <Card><Pressable onPress={details} accessibilityLabel={`View ${p.title}`}><Image source={imageSource(p.photos[0])} style={{height:190,width:'100%'}} contentFit="cover" priority="high" transition={0}/><View style={{position:'absolute',top:12,left:12}}><Badge color={c.green} bg={c.greenBg}>{p.status}</Badge></View><View style={{padding:17,gap:7}}><Row style={{justifyContent:'space-between'}}><T size={21} weight="extra">{money(p.price,true)}{p.purpose==='Rent'&&<T size={11} color={c.muted}> / month</T>}</T><IconButton name={saved?'bookmark':'bookmark-outline'} color={saved?c.primary:c.muted} label={saved?'Unsave property':'Save property'} onPress={()=>s.toggleSave(p.id)}/></Row><T size={14} weight="bold" numberOfLines={1}>{p.beds>0?`${p.beds} BHK `:''}{p.type} in {p.locality}</T><Row style={{gap:4}}><Icon name="location-outline" size={13}/><T size={11} color={c.muted}>{p.city}, {p.state}</T></Row><Row style={{gap:18,marginTop:5}}><T size={11} color={c.muted}>{p.area.toLocaleString()} sq ft</T>{p.beds>0&&<T size={11} color={c.muted}>{p.beds} beds · {p.baths} baths</T>}</Row></View></Pressable></Card>;
 return <Card style={{marginBottom:20}}>
  <Row style={{padding:18,paddingBottom:14,gap:11}}><Pressable onPress={()=>ui.open('seller',p.ownerId)}><Avatar source={p.sellerPhoto} size={42}/></Pressable><View style={{flex:1}}><Row style={{gap:6}}><Pressable onPress={()=>ui.open('seller',p.ownerId)}><T size={13} weight="bold">{p.seller}</T></Pressable>{p.verified&&<Icon name="checkmark-circle" size={14} color={c.primary}/>}<T size={10} color={c.muted}>· {p.demo?'Demo agent':'Seller'}</T></Row><T size={10} color={c.muted}>{p.sellerRole} <T size={10} color={c.muted}> · {p.id==='pavera-1001'?'2h':'Recently'} · </T><Icon name="globe-outline" size={10}/></T></View><IconButton name="ellipsis-horizontal" label="Property options" onPress={()=>ui.open('report',p.id)}/></Row>
  <View style={{paddingHorizontal:18,paddingBottom:13}}><T size={14} weight="semi">{p.title}</T><T size={11} color={c.muted} style={{marginTop:3}} numberOfLines={1}>{p.beds>0?`${p.beds} BHK ${p.type.toLowerCase()}`:p.type} in {p.locality}, {p.city}. {p.available}.</T></View>
  <View><Pressable onPress={details} accessibilityRole="button" accessibilityLabel={`View property photos and details for ${p.beds} BHK ${p.type}, ${money(p.price)}, ${p.city}`}><Image source={imageSource(p.photos[imageIndex])} style={{width:'100%',height:286}} contentFit="cover" priority="high" transition={0}/></Pressable>
   <Row style={{position:'absolute',top:14,left:15,gap:7}}><Badge bg="#FFFFFFF2" color="#2A6D58" icon="ellipse">{p.status.toUpperCase()}</Badge>{p.featured&&<Badge bg="#2C345BDF" color="#fff" icon="sparkles">FEATURED</Badge>}</Row>
   <Pressable onPress={()=>s.toggleSave(p.id)} accessibilityLabel={saved?'Unsave property':'Save property'} style={{position:'absolute',right:15,top:13,width:34,height:34,borderRadius:18,backgroundColor:'#FFFFFFEF',alignItems:'center',justifyContent:'center'}}><Icon name={saved?'bookmark':'bookmark-outline'} color={saved?c.primary:'#434963'} size={17}/></Pressable>
   {p.photos.length>1&&<><View style={{position:'absolute',right:12,bottom:12}}><Pressable onPress={details} accessibilityLabel="Open all property photos"><Badge bg="#18203BC9" color="#fff" icon="images-outline">{imageIndex+1}/{p.photos.length} photos</Badge></Pressable></View><Row style={{position:'absolute',bottom:16,alignSelf:'center',gap:5}}>{p.photos.map((_,i)=><Pressable accessibilityLabel={`Show photo ${i+1}`} key={i} onPress={()=>setImageIndex(i)} style={{padding:3}}><View style={{width:i===imageIndex?17:5,height:5,borderRadius:5,backgroundColor:i===imageIndex?'white':'#FFFFFF80'}}/></Pressable>)}</Row></>}
  </View>
  <View style={{paddingHorizontal:18,paddingTop:16,paddingBottom:13}}><Row style={{justifyContent:'space-between',alignItems:'flex-start',gap:10}}><View style={{flex:1}}><Pressable onPress={details}><T size={16} weight="bold">{p.beds>0?`${p.beds} BHK `:''}{p.type} in {p.locality}</T></Pressable><Row style={{gap:4,marginTop:4}}><Icon name="location-outline" size={13}/><T size={11} color={c.muted}>{p.locality}, {p.city}</T></Row></View><View style={{alignItems:'flex-end'}}><T size={22} weight="extra" color={c.navy} style={{lineHeight:27,letterSpacing:-.6}}>{money(p.price,true)}</T><T size={9} color={c.muted}>{p.purpose==='Rent'?'per month':`₹${Math.round(p.price/p.area).toLocaleString('en-IN')} / sq ft`}</T></View></Row>
  <Row style={{marginTop:14,gap:15,flexWrap:'wrap'}}>{[["expand-outline",`${p.area.toLocaleString()} sq ft`],...(p.beds>0?[["bed-outline",`${p.beds} Beds`]]:[]),["water-outline",`${p.baths} Baths`],["car-outline",`${p.parking} Parking`]].map(([icon,label])=><Row key={label} style={{gap:5}}><Icon name={icon} size={14} color={c.muted}/><T size={10} color={c.muted}>{label}</T></Row>)}</Row></View>
  <Row style={{paddingHorizontal:18,paddingBottom:11,justifyContent:'space-between'}}><Pressable onPress={()=>s.toggleLike(p.id)}><Row style={{gap:5}}><View style={{width:16,height:16,borderRadius:8,backgroundColor:c.tint,justifyContent:'center',alignItems:'center'}}><Icon name="heart" size={9} color={c.primary}/></View><T size={10} color={c.muted}>{p.likes+(liked?1:0)} people love this place</T></Row></Pressable><Pressable onPress={()=>ui.open('comments',p.id)}><T size={10} color={c.muted}>{comments} comments</T></Pressable></Row>
  <Row style={{borderTopWidth:1,borderColor:c.line,marginHorizontal:18,paddingVertical:11,gap:2}}>{[{icon:liked?'heart':'heart-outline',label:'Like',fn:()=>s.toggleLike(p.id),active:liked},{icon:'chatbubble-outline',label:'Comment',fn:()=>ui.open('comments',p.id)},{icon:'arrow-redo-outline',label:'Share',fn:()=>ui.open('share',p.id)}].map(a=><Pressable key={a.label} onPress={a.fn} accessibilityRole="button" accessibilityLabel={a.label} style={({hovered}:any)=>({flexDirection:'row',alignItems:'center',gap:6,padding:8,paddingHorizontal:9,borderRadius:6,backgroundColor:hovered?c.input:'transparent'})}><Icon name={a.icon} size={17} color={a.active?c.primary:c.muted}/><T size={10} weight="semi" color={a.active?c.primary:c.muted}>{a.label}</T></Pressable>)}<View style={{flex:1}}/><Button title="Contact seller" icon="chatbubbles-outline" small variant="tint" onPress={()=>ui.chat(p)}/></Row>
 </Card>
}
