import React from 'react';
import {Pressable,View} from 'react-native';
import {Image} from 'expo-image';
import {LinearGradient} from 'expo-linear-gradient';
import {useStore} from '../lib/store';
import {useUI} from '../lib/navigation';
import {useTheme} from '../lib/theme';
import {imageSource,photos} from '../lib/data';
import {Route} from '../lib/types';
import {Avatar,Button,Card,Icon,Row,T} from './ui';
export default function Sidebar({route}:{route:Route}){const{c}=useTheme();const s=useStore();const ui=useUI();const p=s.profile;const navs:[string,any,Route,number?][]=[['Home feed','grid-outline','Home'],['Explore properties','compass-outline','Explore'],['Saved properties','bookmark-outline','Saved',s.saved.length],['My listings','business-outline','Dashboard'],['Messages','chatbubbles-outline','Messages',s.conversations.reduce((n,c)=>n+c.unread,0)],['Payments','wallet-outline','Payments']];return <View style={{width:222,gap:18}}>
 <Card><View style={{height:73}}><Image source={imageSource(p?.cover||photos.house)} style={{width:'100%',height:'100%'}} contentFit="cover"/><LinearGradient colors={['#25335A08','#243B5280']} style={{position:'absolute',inset:0} as any}/></View><View style={{padding:18,paddingTop:0}}><Pressable onPress={()=>p?ui.navigate('Profile'):ui.open('auth')}><Avatar source={p?.photo||photos.arjun} size={61} style={{marginTop:-29,borderWidth:4,borderColor:c.card}}/><T size={17} weight="extra" style={{marginTop:7}}>{p?.name||'Welcome to Pavera'}</T></Pressable><T size={10} color={c.muted} style={{marginTop:2}}>{p?`${p.role} · Finding my next home`:'A fresh start, a new address.'}</T><Row style={{gap:4,marginTop:8}}><Icon name="location-outline" size={12}/><T size={10} color={c.muted}>{p?.city||'Made for your next chapter'}</T></Row><View style={{height:1,backgroundColor:c.line,marginVertical:15}}/><Row style={{justifyContent:'space-between'}}><Pressable onPress={()=>ui.navigate('Saved')}><T size={16} weight="bold">{s.saved.length.toString().padStart(2,'0')}</T><T size={9} color={c.muted}>Saved places</T></Pressable><View style={{height:28,width:1,backgroundColor:c.line}}/><Pressable onPress={()=>ui.navigate('Dashboard')}><T size={16} weight="bold">{s.properties.filter(x=>x.ownerId===p?.id).length.toString().padStart(2,'0')}</T><T size={9} color={c.muted}>My listings</T></Pressable></Row></View><Pressable onPress={()=>p?ui.navigate('Profile'):ui.open('auth')} style={{borderTopWidth:1,borderColor:c.line,padding:11,alignItems:'center'}}><T size={10} weight="bold" color={c.primary}>{p?'View my profile':'Sign in to your account'} <Icon name="arrow-forward" size={11} color={c.primary}/></T></Pressable></Card>
 <Card style={{padding:10,paddingVertical:12}}>{navs.map(([label,icon,key,count],i)=><React.Fragment key={key}>{i===4&&<View style={{height:1,backgroundColor:c.line,margin:10}}/>}<Pressable onPress={()=>ui.navigate(key)} accessibilityRole="button" style={({hovered}:any)=>({flexDirection:'row',alignItems:'center',gap:12,paddingHorizontal:12,paddingVertical:12,borderRadius:8,backgroundColor:route===key?c.tint:hovered?c.input:'transparent',marginBottom:3})}><Icon name={route===key?icon.replace('-outline',''):icon} size={18} color={route===key?c.primary:c.muted}/><T size={11} weight={route===key?'bold':'medium'} color={route===key?c.primary:c.text} style={{flex:1}}>{label}</T>{!!count&&<View style={{minWidth:19,height:19,borderRadius:5,backgroundColor:route===key?c.card:c.input,alignItems:'center',justifyContent:'center'}}><T size={9} weight="bold" color={c.primary}>{count}</T></View>}</Pressable></React.Fragment>)}<Pressable onPress={()=>ui.navigate('Settings')} style={{padding:12,flexDirection:'row',alignItems:'center',gap:12}}><Icon name="settings-outline" size={18}/><T size={11} color={c.muted}>Settings & help</T></Pressable></Card>
 <Card style={{backgroundColor:c.tint,borderColor:'#E3E6F6',padding:18}}><Row style={{justifyContent:'space-between',marginBottom:9}}><T size={9} weight="extra" color={c.primary} style={{letterSpacing:1.3}}>A NEW BEGINNING</T><Icon name="home-outline" size={27} color={c.primary}/></Row><T size={17} weight="bold" style={{lineHeight:24}}>Your property.{'\n'}Someone’s perfect place.</T><T size={10} color={c.muted} style={{marginTop:7,marginBottom:15}}>Connect with people ready for their next chapter.</T><Button title="List your property" icon="add-outline" small onPress={()=>p?ui.open('sell'):ui.open('auth')}/><T size={8} color={c.muted} style={{textAlign:'center',marginTop:9}}>A little effort. A lot of possibility.</T></Card>
 </View>}
