import React from 'react';
import {ActivityIndicator,Modal,Platform,Pressable,StyleSheet,Text,TextInput,TextInputProps,View,ViewStyle,ScrollView,KeyboardAvoidingView,useWindowDimensions} from 'react-native';
import {Image} from 'expo-image';
import Ionicons from '@expo/vector-icons/Ionicons';
import {SafeAreaView} from 'react-native-safe-area-context';
import {fonts,useTheme} from '../lib/theme';
import {imageSource} from '../lib/data';
import {useStore} from '../lib/store';
export function Icon({name,size=20,color,...props}:{name:any;size?:number;color?:string;[k:string]:any}){const{c}=useTheme();return <Ionicons name={name} size={size} color={color||c.muted} accessible={false} aria-hidden={true} {...props}/>}
export function T({children,size=14,color,weight='regular',style,numberOfLines,...rest}:any){const{c}=useTheme();return <Text {...rest} numberOfLines={numberOfLines} style={[{fontFamily:fonts[weight as keyof typeof fonts]||fonts.regular,fontSize:size,color:color||c.text,lineHeight:size*1.55},style]}>{children}</Text>}
export function Row({children,style}:any){return <View style={[{flexDirection:'row',alignItems:'center'},style]}>{children}</View>}
export function Card({children,style}:any){const{c}=useTheme();return <View style={[{backgroundColor:c.card,borderWidth:1,borderColor:c.line,borderRadius:14,overflow:'hidden',shadowColor:'#1B244B',shadowOffset:{width:0,height:2},shadowOpacity:.018,shadowRadius:6},style]}>{children}</View>}
export function Button({title,onPress,icon,variant='primary',small=false,loading=false,disabled=false,style}:any){const{c,dark}=useTheme();const outlined=variant==='outline',ghost=variant==='ghost',tint=variant==='tint';const color=ghost||outlined||tint?c.primary:variant==='danger'?'#fff':dark?'#18213D':'#fff';return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled||loading} onPress={onPress} style={({pressed,hovered}:any)=>[{paddingVertical:small?9:12,paddingHorizontal:small?14:20,minHeight:small?36:44,borderRadius:8,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:8,backgroundColor:ghost?'transparent':outlined?c.card:tint?c.tint:variant==='danger'?c.danger:c.primary,borderWidth:outlined?1:0,borderColor:c.line,opacity:disabled?.45:pressed?.7:hovered?.88:1},style]}>{loading?<ActivityIndicator size="small" color={color}/>:icon?<Icon name={icon} size={small?16:18} color={color}/>:null}<T size={small?11:12} weight="bold" color={color} style={{flexShrink:1,textAlign:'center'}}>{title}</T></Pressable>}
export function IconButton({name,onPress,label,size=20,style,color}:any){const{c}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={label||name} onPress={onPress} style={({pressed,hovered}:any)=>[{width:36,height:36,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:pressed||hovered?c.tint:'transparent'},style]}><Icon name={name} size={size} color={color}/></Pressable>}
export function Avatar({source,size=42,style}:any){const{c}=useTheme();return <Image source={imageSource(source)} style={[{width:size,height:size,borderRadius:size/2,backgroundColor:c.tint},style]} contentFit="cover" transition={0}/>}
export function Badge({children,color,bg,icon}:any){const{c}=useTheme();return <Row style={{alignSelf:'flex-start',backgroundColor:bg||c.tint,paddingHorizontal:9,paddingVertical:4,borderRadius:5,gap:4}}>{icon&&<Icon name={icon} size={11} color={color||c.primary}/>}<T size={10} weight="bold" color={color||c.primary}>{children}</T></Row>}
export function Field({label,error,style,...props}:TextInputProps&{label?:string;error?:string;style?:any}){const{c}=useTheme();return <View style={{flex:1,minWidth:110,gap:7,...style}}>{label&&<T size={12} weight="semi">{label}</T>}<TextInput accessibilityLabel={props.accessibilityLabel||label||props.placeholder} placeholderTextColor={c.muted} returnKeyType="next" {...props} style={[{fontFamily:fonts.regular,fontSize:13,color:c.text,backgroundColor:c.input,borderColor:error?c.danger:c.line,borderWidth:1,borderRadius:8,paddingHorizontal:13,paddingVertical:12,minHeight:44,textAlignVertical:props.multiline?'top':'center',outlineStyle:'none'} as any,props.multiline&&{minHeight:100}]}/>{error&&<T size={10} color={c.danger}>{error}</T>}</View>}
export function Chips({items,value,onChange,multiple=false}:any){const{c}=useTheme();return <Row style={{flexWrap:'wrap',gap:7}}>{items.map((item:string)=>{const active=multiple?value.includes(item):value===item;return <Pressable accessibilityRole="button" accessibilityState={{selected:active}} key={item} onPress={()=>onChange(multiple?(active?value.filter((i:string)=>i!==item):[...value,item]):item)} style={({hovered}:any)=>({borderWidth:1,borderColor:active?c.primary:c.line,backgroundColor:active?c.tint:hovered?c.input:c.card,paddingVertical:8,paddingHorizontal:12,borderRadius:7})}><T size={11} weight={active?'bold':'medium'} color={active?c.primary:c.muted}>{item}</T></Pressable>})}</Row>}
export function Empty({icon='search-outline',title,body,action,onAction}:any){const{c}=useTheme();return <View style={{alignItems:'center',paddingHorizontal:25,paddingVertical:65,gap:12}}><View style={{width:70,height:70,borderRadius:22,alignItems:'center',justifyContent:'center',backgroundColor:c.tint}}><Icon name={icon} size={30} color={c.primary}/></View><T size={20} weight="bold" style={{textAlign:'center'}}>{title}</T><T size={12} color={c.muted} style={{textAlign:'center',maxWidth:350}}>{body}</T>{action&&<Button title={action} onPress={onAction} style={{marginTop:8}}/>}</View>}
export function SectionTitle({title,subtitle,action,onAction}:any){const{c}=useTheme();return <Row style={{justifyContent:'space-between',marginBottom:22,gap:12}}><View style={{flex:1}}><T size={26} weight="extra" style={{letterSpacing:-.8}}>{title}</T>{subtitle&&<T size={12} color={c.muted} style={{marginTop:5}}>{subtitle}</T>}</View>{action&&<Button title={action} small onPress={onAction}/>}</Row>}
export function ModalFrame({title,subtitle,children,onClose,wide=false,footer,scroll=true}:any){const{c}=useTheme();const{toast}=useStore();const{width}=useWindowDimensions();return <Modal visible animationType="fade" transparent onRequestClose={onClose}><View style={{flex:1,backgroundColor:'#141B3B88',alignItems:'center',justifyContent:'center',padding:width<700?0:24}}><Pressable accessibilityLabel="Close dialog" onPress={onClose} style={StyleSheet.absoluteFill}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{width:'100%',maxWidth:wide?960:570,maxHeight:width<700?'100%':'94%',height:width<700?'100%':undefined,backgroundColor:c.card,borderRadius:width<700?0:18,overflow:'hidden',borderColor:c.line,borderWidth:1}}><SafeAreaView edges={width<700?['top','bottom']:[]} style={{flexShrink:1,flexGrow:width<700?1:0}}><Row style={{paddingHorizontal:24,paddingVertical:19,borderBottomWidth:1,borderColor:c.line,justifyContent:'space-between'}}><View style={{flex:1}}><T size={20} weight="bold">{title}</T>{subtitle&&<T size={11} color={c.muted} style={{marginTop:2}}>{subtitle}</T>}</View><IconButton name="close-outline" label="Close dialog" onPress={onClose}/></Row>{scroll?<ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={{padding:24,gap:20}}>{children}</ScrollView>:children}{footer&&<View style={{padding:20,borderTopWidth:1,borderColor:c.line}}>{footer}</View>}</SafeAreaView>{!!toast&&<View pointerEvents="none" style={{position:'absolute',bottom:footer?95:18,left:18,right:18,alignItems:'center'}}><Row style={{backgroundColor:'#283252',padding:13,borderRadius:9,gap:9,maxWidth:'100%'}}><Icon name="information-circle-outline" color="#B2DCCB" size={18}/><T size={11} color="#fff" style={{flexShrink:1}}>{toast}</T></Row></View>}</KeyboardAvoidingView></View></Modal>}
export function NoticeBox({children,icon='information-circle-outline',style}:any){const{c}=useTheme();return <Row style={{padding:14,backgroundColor:c.tint,borderRadius:9,gap:11,alignItems:'flex-start',...style}}><Icon name={icon} size={19} color={c.primary}/><T size={11} color={c.primary} style={{flex:1,lineHeight:18}}>{children}</T></Row>}
export function Skeleton(){const{c}=useTheme();return <Card style={{padding:20,gap:16}}><Row style={{gap:12}}><View style={{width:44,height:44,borderRadius:24,backgroundColor:c.line}}/><View style={{height:13,width:'40%',backgroundColor:c.line,borderRadius:5}}/></Row><View style={{height:260,backgroundColor:c.input,borderRadius:10}}/><View style={{height:16,width:'70%',backgroundColor:c.line,borderRadius:5}}/></Card>}
