import { Profile, Property, Notice, Filters } from './types';
export const photos = {
 living:require('../assets/images/living-room.jpg'), villa:require('../assets/images/villa.jpg'), apartment:require('../assets/images/apartment.jpg'), bedroom:require('../assets/images/bedroom.jpg'), kitchen:require('../assets/images/kitchen.jpg'), house:require('../assets/images/house.jpg'), office:require('../assets/images/office.jpg'), land:require('../assets/images/land.jpg'), shop:require('../assets/images/shop.jpg'), bhopal:require('../assets/images/bhopal.jpg'), indore:require('../assets/images/indore.jpg'), arjun:require('../assets/images/arjun.jpg'), priya:require('../assets/images/priya.jpg'), rahul:require('../assets/images/rahul.jpg'), neha:require('../assets/images/neha.jpg'),
};
export const demoProfile:Profile={id:'demo-arjun',name:'Arjun Mehta',role:'Buyer',bio:'Finding a little more space for the things that matter. Exploring homes in Bhopal.',city:'Bhopal, Madhya Pradesh',email:'arjun@example.com',phone:'',photo:photos.arjun,cover:photos.house,verified:false};
export const propertyTypes=['Apartment','Villa','House','Plot / Land','Office','Shop','Commercial'];
export const amenities=['Security','Lift','Power backup','Gym','Swimming pool','Garden','Clubhouse','Visitor parking','Children’s play area','Wi-Fi'];
const base:Property={id:'',ownerId:'demo-priya',title:'',type:'Apartment',purpose:'Sale',price:7500000,area:1450,address:'E-8, Arera Colony',locality:'Arera Colony',city:'Bhopal',state:'Madhya Pradesh',pin:'462016',beds:3,baths:2,parking:1,floor:4,floors:8,furnishing:'Semi-furnished',age:'1–3 years',amenities:['Security','Lift','Power backup','Gym','Garden'],description:'A home that feels like a deep breath. Thoughtfully designed spaces, abundant natural light, and a neighborhood you’ll love coming back to. This spacious residence combines contemporary finishes with everyday comfort, with schools, cafés, and essentials close by. Arrange a visit to discover the space for yourself.',phone:'',status:'For Sale',available:'Ready to move',photos:[photos.living,photos.bedroom,photos.kitchen],seller:'Priya Sharma',sellerPhoto:photos.priya,sellerRole:'Real estate consultant',verified:false,featured:true,demo:true,createdAt:'2026-09-30T07:30:00Z',likes:24,bookingAmount:10000};
export const initialProperties:Property[]=[
 {...base,id:'pavera-1001',title:'A little more room. A lot more life.',price:7500000},
 {...base,id:'pavera-1002',ownerId:'demo-rahul',title:'Your own corner of extraordinary.',type:'Villa',price:18500000,area:2800,beds:4,baths:4,parking:2,floor:0,floors:2,locality:'Nipania',address:'Nipania Main Road',city:'Indore',pin:'452010',photos:[photos.villa,photos.kitchen,photos.bedroom],seller:'Rahul Verma',sellerPhoto:photos.rahul,sellerRole:'Independent property advisor',likes:38,createdAt:'2026-09-30T06:00:00Z',furnishing:'Fully furnished'},
 {...base,id:'pavera-1003',ownerId:'demo-neha',title:'City living, with room to unwind.',purpose:'Rent',status:'For Rent',price:24000,area:1100,beds:2,baths:2,locality:'Vijay Nagar',address:'Scheme No. 54, Vijay Nagar',city:'Indore',pin:'452010',photos:[photos.apartment,photos.bedroom,photos.kitchen],seller:'Neha Kapoor',sellerPhoto:photos.neha,sellerRole:'Property owner',featured:false,likes:17,createdAt:'2026-09-29T15:00:00Z'},
 {...base,id:'pavera-1004',title:'A beautiful place to put down roots.',type:'House',price:11200000,area:2200,beds:4,baths:3,locality:'Kolar Road',address:'Danish Kunj, Kolar Road',pin:'462042',photos:[photos.house,photos.living,photos.kitchen],likes:31,createdAt:'2026-09-29T12:00:00Z'},
 {...base,id:'pavera-1005',title:'Build your dream, from the ground up.',type:'Plot / Land',price:4200000,area:2400,beds:0,baths:0,parking:0,floor:0,floors:0,locality:'Airport Road',address:'Airport Road',pin:'462030',photos:[photos.land],amenities:['Security','Garden'],furnishing:'Unfurnished',featured:false,likes:9,createdAt:'2026-09-28T11:00:00Z'},
 {...base,id:'pavera-1006',ownerId:'demo-rahul',title:'Big ideas deserve a better workspace.',type:'Office',purpose:'Rent',status:'For Rent',price:65000,area:1800,beds:0,baths:2,parking:3,locality:'MP Nagar',address:'Zone II, MP Nagar',pin:'462011',photos:[photos.office],seller:'Rahul Verma',sellerPhoto:photos.rahul,amenities:['Security','Lift','Power backup','Wi-Fi'],featured:false,likes:12,createdAt:'2026-09-28T09:00:00Z'},
 {...base,id:'pavera-1007',title:'The perfect address for your next venture.',type:'Shop',price:5500000,area:650,beds:0,baths:1,locality:'New Market',address:'TT Nagar, New Market',pin:'462003',photos:[photos.shop],featured:false,likes:6,createdAt:'2026-09-27T10:00:00Z'},
 {...base,id:'pavera-1008',title:'A landmark space for a growing business.',type:'Commercial',price:22500000,area:4500,beds:0,baths:4,parking:6,locality:'Vijay Nagar',city:'Indore',address:'AB Road, Vijay Nagar',pin:'452010',photos:[photos.office,photos.indore],featured:false,likes:14,createdAt:'2026-09-26T10:00:00Z'}
];
export const initialNotices:Notice[]=[{id:'welcome',title:'Welcome to your next chapter',body:'Explore Pavera’s demo workspace. Save a home, try a listing, and make yourself at home.',type:'system',read:false,createdAt:'2026-09-30T08:00:00Z'},{id:'curated',title:'A few places you might love',body:'Discover thoughtfully selected demo properties in Bhopal and Indore.',type:'listing',read:false,createdAt:'2026-09-30T07:00:00Z',propertyId:'pavera-1001'}];
export const emptyFilters:Filters={purpose:'All',type:'All types',city:'All locations',minPrice:'',maxPrice:'',minArea:'',maxArea:'',beds:'Any',baths:'Any',furnishing:'Any',parking:false,amenities:[],status:'Active',sort:'Recommended'};
export const money=(n:number,short=false)=>short?(n>=10000000?`₹${(n/10000000).toFixed(2).replace(/0$/,'')} Cr`:n>=100000?`₹${(n/100000).toFixed(0)} Lac`:`₹${n.toLocaleString('en-IN')}`):`₹${n.toLocaleString('en-IN')}`;
export const imageSource=(p:any)=>typeof p==='string'?{uri:p}:p;
export function filterProperties(properties:Property[],query:string,f:Filters){
 const q=query.toLowerCase().trim();
 const list=properties.filter(p=>{
  if(f.status==='Active'&&!['For Sale','For Rent'].includes(p.status))return false;
  if(f.status!=='Active'&&f.status!=='All'&&p.status!==f.status)return false;
  if(q&&!`${p.title} ${p.type} ${p.city} ${p.locality} ${p.address} ${p.beds} BHK`.toLowerCase().includes(q))return false;
  return(f.purpose==='All'||p.purpose===f.purpose)&&(f.type==='All types'||p.type===f.type)&&(f.city==='All locations'||p.city===f.city)&&(!f.minPrice||p.price>=Number(f.minPrice))&&(!f.maxPrice||p.price<=Number(f.maxPrice))&&(!f.minArea||p.area>=Number(f.minArea))&&(!f.maxArea||p.area<=Number(f.maxArea))&&(f.beds==='Any'||p.beds>=Number(f.beds))&&(f.baths==='Any'||p.baths>=Number(f.baths))&&(f.furnishing==='Any'||p.furnishing===f.furnishing)&&(!f.parking||p.parking>0)&&f.amenities.every(a=>p.amenities.includes(a));
 });
 return list.sort((a,b)=>f.sort==='Price: low to high'?a.price-b.price:f.sort==='Price: high to low'?b.price-a.price:f.sort==='Area: low to high'?a.area-b.area:f.sort==='Area: high to low'?b.area-a.area:f.sort==='Newest'?Date.parse(b.createdAt)-Date.parse(a.createdAt):Number(b.featured)-Number(a.featured));
}
