import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Comment,Conversation,Notice,Payment,Profile,Property,Report} from './types';
import {demoProfile,initialNotices,initialProperties,photos} from './data';
import {supabase} from './backend';
export const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2,10)}`;
const now=()=>new Date().toISOString();
interface Workspace { properties:Property[]; saved:string[]; liked:string[]; comments:Comment[]; conversations:Conversation[]; notifications:Notice[]; reports:Report[]; payments:Payment[]; recent:string[]; following:string[]; profile:Profile|null; }
const seed=():Workspace=>({properties:initialProperties,saved:[],liked:[],comments:[],conversations:[{id:'demo-conversation',propertyId:'pavera-1001',sellerId:'demo-priya',seller:'Priya Sharma',photo:photos.priya,messages:[{id:'demo-msg',senderId:'demo-priya',text:'Hi Arjun! Welcome to Pavera. This is a sample conversation — your real property conversations will appear here once live messaging is connected.',createdAt:'2026-09-30T07:30:00Z',read:false}],archived:false,unread:1}],notifications:initialNotices,reports:[],payments:[],recent:[],following:[],profile:demoProfile});
type Confirmation={title:string;body:string;action:string;onConfirm:()=>void;danger?:boolean};
interface Store extends Workspace {loading:boolean;error:string;demo:boolean;adminPreview:boolean;setAdminPreview:(v:boolean)=>void;toast:string;notify:(s:string)=>void;confirmation:Confirmation|null;confirm:(c:Confirmation|null)=>void;refresh:()=>Promise<void>;toggleSave:(id:string)=>Promise<void>;toggleLike:(id:string)=>Promise<void>;addComment:(id:string,text:string)=>Promise<void>;deleteComment:(id:string)=>Promise<void>;publish:(p:Property)=>Promise<boolean>;removeProperty:(id:string)=>Promise<void>;updateProperty:(id:string,p:Partial<Property>)=>Promise<void>;viewProperty:(id:string)=>void;startChat:(p:Property)=>Promise<string|null>;sendMessage:(id:string,text:string,attachment?:string)=>Promise<void>;manageConversation:(id:string,action:'archive'|'delete'|'read')=>Promise<void>;markNotice:(id?:string)=>Promise<void>;deleteNotice:(id:string)=>Promise<void>;addReport:(propertyId:string,reason:string,details:string)=>Promise<void>;resolveReport:(id:string)=>Promise<void>;updateProfile:(p:Partial<Profile>)=>Promise<void>;follow:(name:string)=>void;logout:()=>Promise<void>;enterDemo:()=>void;addNotice:(title:string,body:string,type?:Notice['type'])=>void;}
const Context=createContext<Store>(null as any);
export function StoreProvider({children}:{children:React.ReactNode}){
 const[w,setW]=useState<Workspace>(seed);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[demo,setDemo]=useState(true);const[adminPreview,setAdminPreview]=useState(false);const[toast,notify]=useState('');const[confirmation,confirm]=useState<Confirmation|null>(null);const ready=useRef(false);const busy=useRef(new Set<string>());
 useEffect(()=>{let active=true;AsyncStorage.getItem('pavera-demo-v3').then(v=>{if(v&&active)setW({...seed(),...JSON.parse(v)});}).catch(()=>setError('Your saved workspace could not be loaded. Please retry.')).finally(()=>{ready.current=true;if(active)setLoading(false)});return()=>{active=false}},[]);
 useEffect(()=>{if(ready.current&&demo)AsyncStorage.setItem('pavera-demo-v3',JSON.stringify(w)).catch(()=>notify('Your device storage is full. Changes may not be saved.'))},[w,demo]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>notify(''),3800);return()=>clearTimeout(t)},[toast]);
 const cloudLoad=async(user:any)=>{
  if(!supabase)return;setLoading(true);setError('');setDemo(false);setW(s=>s.profile?.id===user.id?s:{...seed(),profile:{...demoProfile,id:user.id,name:user.user_metadata?.name||'Pavera member',email:user.email||'',role:'Buyer',bio:'',city:'',phone:''},properties:[],saved:[],liked:[],comments:[],conversations:[],notifications:[],payments:[],reports:[],recent:[],following:[]});
  try{const results=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).single(),supabase.from('properties').select('*'),supabase.from('saved_properties').select('property_id'),supabase.from('likes').select('property_id'),supabase.from('comments').select('*'),supabase.from('conversations').select('*,messages(*)'),supabase.from('notifications').select('*').order('created_at',{ascending:false}),supabase.from('payments').select('*'),supabase.from('reports').select('*')]);
   const failure=results.find(r=>r.error);if(failure?.error)throw failure.error;
   const pr=results[0].data;const profile={...demoProfile,...pr,id:user.id,email:user.email,photo:pr.photo||photos.arjun,cover:pr.cover||photos.house};
   setW({profile,properties:(results[1].data??[]).map((p:any)=>({...p.details,id:p.id,ownerId:p.owner_id,title:p.title,status:p.status,purpose:p.purpose,verified:p.verified,featured:p.featured,demo:false})),saved:(results[2].data??[]).map((x:any)=>x.property_id),liked:(results[3].data??[]).map((x:any)=>x.property_id),comments:(results[4].data??[]).map((x:any)=>({id:x.id,propertyId:x.property_id,userId:x.user_id,name:x.name,text:x.text,createdAt:x.created_at})),conversations:(results[5].data??[]).map((x:any)=>({id:x.id,propertyId:x.property_id,sellerId:x.seller_id,seller:x.seller,photo:x.photo||photos.priya,archived:x.archived,unread:x.messages.filter((m:any)=>!m.read&&m.sender_id!==user.id).length,messages:x.messages.map((m:any)=>({id:m.id,senderId:m.sender_id,text:m.text,read:m.read,createdAt:m.created_at,attachment:m.attachment})).sort((a:any,b:any)=>Date.parse(a.createdAt)-Date.parse(b.createdAt))})),notifications:(results[6].data??[]).map((x:any)=>({id:x.id,title:x.title,body:x.body,type:x.type,read:x.read,createdAt:x.created_at,propertyId:x.property_id})),payments:(results[7].data??[]).map((x:any)=>({id:x.id,propertyId:x.property_id,propertyTitle:x.property_title,buyer:x.buyer_name,seller:x.seller_name,amount:x.amount/100,fees:0,method:x.method,status:x.status,transactionId:x.gateway_payment_id||x.gateway_order_id||x.id,createdAt:x.created_at})),reports:(results[8].data??[]).map((x:any)=>({id:x.id,propertyId:x.property_id,reason:x.reason,details:x.details,status:x.status,createdAt:x.created_at,reporterId:x.reporter_id})),recent:[],following:[]});setDemo(false);setAdminPreview(false);
  }catch(e:any){setError(e.message||'Unable to connect. Please try again.')}finally{setLoading(false)}
 };
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>{if(data.session)cloudLoad(data.session.user)});const{data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(session&&['SIGNED_IN','PASSWORD_RECOVERY'].includes(event))setTimeout(()=>cloudLoad(session.user),0)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(demo||!supabase||!w.profile)return;const user=w.profile;const channel=supabase.channel(`workspace-${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'messages'},()=>cloudLoad({id:user.id,email:user.email})).on('postgres_changes',{event:'*',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},()=>cloudLoad({id:user.id,email:user.email})).on('postgres_changes',{event:'*',schema:'public',table:'payments'},()=>cloudLoad({id:user.id,email:user.email})).subscribe();return()=>{supabase?.removeChannel(channel)}},[demo,w.profile?.id]);
 const persist=async(table:string,action:'insert'|'update'|'delete'|'upsert',value:any,match?:Record<string,any>)=>{if(demo)return;if(!supabase)throw Error('Backend is not connected');let query:any=action==='insert'?supabase.from(table).insert(value):action==='upsert'?supabase.from(table).upsert(value):action==='update'?supabase.from(table).update(value):supabase.from(table).delete();if(match)for(const[k,v]of Object.entries(match))query=query.eq(k,v);const{error}=await query;if(error)throw error;};
 const guard=()=>{if(!w.profile){notify('Please sign in or enter the demo workspace to continue.');return false}return true};
 const run=async(key:string,fn:()=>Promise<void>)=>{if(busy.current.has(key))return;busy.current.add(key);try{await fn()}catch(e:any){notify(e.message||'Something went wrong. Please try again.')}finally{busy.current.delete(key)}};
 const addNotice=(title:string,body:string,type:Notice['type']='activity')=>{if(demo)setW(s=>({...s,notifications:[{id:uid(),title,body,type,read:false,createdAt:now()},...s.notifications]}))};
 const toggle=async(id:string,field:'saved'|'liked')=>{if(!guard())return;await run(`${field}-${id}`,async()=>{const exists=w[field].includes(id);await persist(field==='saved'?'saved_properties':'likes',exists?'delete':'insert',{user_id:w.profile!.id,property_id:id},{...(exists?{user_id:w.profile!.id,property_id:id}:{})});setW(s=>({...s,[field]:exists?s[field].filter(x=>x!==id):[...s[field],id]}));if(field==='saved')notify(exists?'Removed from your saved places':'A good find. Saved to your collection.')})};
 const value:Store={...w,loading,error,demo,adminPreview,setAdminPreview,toast,notify,confirmation,confirm,
 refresh:async()=>{if(!demo&&w.profile)await cloudLoad({id:w.profile.id,email:w.profile.email});else{setLoading(true);await new Promise(r=>setTimeout(r,450));setError('');setLoading(false)}},
 toggleSave:id=>toggle(id,'saved'),toggleLike:id=>toggle(id,'liked'),
 addComment:async(id,text)=>{if(!guard()||!text.trim())return;await run('comment',async()=>{const c:Comment={id:uid(),propertyId:id,userId:w.profile!.id,name:w.profile!.name,text:text.trim().slice(0,2000),createdAt:now()};await persist('comments','insert',{id:c.id,property_id:id,user_id:c.userId,name:c.name,text:c.text});setW(s=>({...s,comments:[...s.comments,c]}));notify(demo?'Comment added to the demo workspace':'Comment posted')})},
 deleteComment:async id=>{const c=w.comments.find(c=>c.id===id);if(c?.userId!==w.profile?.id)return;await run(id,async()=>{await persist('comments','delete',null,{id});setW(s=>({...s,comments:s.comments.filter(c=>c.id!==id)}))})},
 publish:async p=>{if(!guard())return false;if(p.ownerId!==w.profile!.id&&!adminPreview&&w.profile?.role!=='Admin')return false;let success=false;await run('publish',async()=>{await persist('properties','upsert',{id:p.id,owner_id:p.ownerId,title:p.title,purpose:p.purpose,status:demo?p.status:(p.status==='Draft'?'Draft':'Under Review'),details:p});setW(s=>({...s,properties:[p,...s.properties.filter(x=>x.id!==p.id)]}));addNotice(p.status==='Draft'?'Draft saved':'Your listing is ready',p.status==='Draft'?'Pick up where you left off in My listings.':demo?'Your property is now visible in this demo workspace.':'Your listing is awaiting moderation.','listing');notify(p.status==='Draft'?'Draft saved. Your ideas are safe.':demo?'Your property is published in the demo workspace!':'Listing submitted for review.');success=true});return success},
 removeProperty:async id=>{const p=w.properties.find(p=>p.id===id);if(p?.ownerId!==w.profile?.id&&!adminPreview&&w.profile?.role!=='Admin')return;await run(id,async()=>{await persist('properties','delete',null,{id});setW(s=>({...s,properties:s.properties.filter(p=>p.id!==id),saved:s.saved.filter(x=>x!==id)}));notify('Listing deleted')})},
 updateProperty:async(id,patch)=>{const p=w.properties.find(p=>p.id===id);if(!p||(p.ownerId!==w.profile?.id&&!adminPreview&&w.profile?.role!=='Admin'))return;await run(id,async()=>{await persist('properties','update',{...(Object.keys(patch).some(k=>!['status','verified','featured'].includes(k))?{details:{...p,...patch}}:{}),...(patch.status?{status:patch.status}:{}),...(patch.verified!==undefined?{verified:patch.verified}:{}),...(patch.featured!==undefined?{featured:patch.featured}:{})},{id});setW(s=>({...s,properties:s.properties.map(p=>p.id===id?{...p,...patch}:p)}));notify('Listing updated')})},
 viewProperty:id=>setW(s=>({...s,recent:[id,...s.recent.filter(x=>x!==id)].slice(0,12)})),
 startChat:async p=>{if(!guard())return null;if(p.ownerId===w.profile?.id){notify('This is your listing. View buyer inquiries in My listings.');return null}const found=w.conversations.find(c=>c.propertyId===p.id&&c.sellerId===p.ownerId);if(found){setW(s=>({...s,conversations:s.conversations.map(c=>c.id===found.id?{...c,archived:false,unread:0}:c)}));return found.id}const c:Conversation={id:uid(),propertyId:p.id,sellerId:p.ownerId,seller:p.seller,photo:p.sellerPhoto,messages:[],archived:false,unread:0};let success=false;await run('chat',async()=>{await persist('conversations','insert',{id:c.id,property_id:p.id,buyer_id:w.profile!.id,seller_id:p.ownerId,seller:p.seller,photo:typeof p.sellerPhoto==='string'?p.sellerPhoto:null});setW(s=>({...s,conversations:[c,...s.conversations]}));success=true});return success?c.id:null},
 sendMessage:async(id,text,attachment)=>{if(!guard()||(!text.trim()&&!attachment))return;await run('send',async()=>{const m={id:uid(),text:text.trim().slice(0,4000),senderId:w.profile!.id,createdAt:now(),read:false,attachment};await persist('messages','insert',{id:m.id,conversation_id:id,sender_id:m.senderId,text:m.text,attachment:m.attachment});setW(s=>({...s,conversations:s.conversations.map(c=>c.id===id?{...c,messages:[...c.messages,m]}:c)}))})},
 manageConversation:async(id,action)=>{await run(id,async()=>{if(action==='read'){if(!demo&&supabase){const{error}=await supabase.from('messages').update({read:true}).eq('conversation_id',id).neq('sender_id',w.profile?.id).eq('read',false);if(error)throw error}}else await persist('conversations',action==='delete'?'delete':'update',{archived:!w.conversations.find(c=>c.id===id)?.archived},{id});setW(s=>({...s,conversations:action==='delete'?s.conversations.filter(c=>c.id!==id):s.conversations.map(c=>c.id===id?{...c,...(action==='archive'?{archived:!c.archived}:{unread:0,messages:c.messages.map(m=>m.senderId!==w.profile?.id?{...m,read:true}:m)})}:c)}))})},
 markNotice:async id=>{await run('notice',async()=>{await persist('notifications','update',{read:true},id?{id}:{user_id:w.profile?.id});setW(s=>({...s,notifications:s.notifications.map(n=>!id||n.id===id?{...n,read:true}:n)}))})},
 deleteNotice:async id=>{await run(id,async()=>{await persist('notifications','delete',null,{id});setW(s=>({...s,notifications:s.notifications.filter(n=>n.id!==id)}))})},
 addReport:async(propertyId,reason,details)=>{if(!guard())return;await run('report',async()=>{const r:Report={id:uid(),propertyId,reason,details,status:'Open',createdAt:now(),reporterId:w.profile!.id};await persist('reports','insert',{id:r.id,property_id:propertyId,reason,details,reporter_id:r.reporterId});setW(s=>({...s,reports:[r,...s.reports]}));notify(demo?'Report saved to the demo admin inbox':'Report sent to the moderation team')})},
 resolveReport:async id=>{if(!adminPreview&&w.profile?.role!=='Admin')return;await run(id,async()=>{await persist('reports','update',{status:'Resolved'},{id});setW(s=>({...s,reports:s.reports.map(r=>r.id===id?{...r,status:'Resolved'}:r)}));notify('Report resolved')})},
 updateProfile:async patch=>{if(!guard())return;await run('profile',async()=>{const safe={...patch};delete safe.id;delete safe.verified;if(safe.role==='Admin')delete safe.role;const remote:any={...safe};if(typeof remote.photo==='number')delete remote.photo;if(typeof remote.cover==='number')delete remote.cover;await persist('profiles','update',remote,{id:w.profile!.id});setW(s=>({...s,profile:s.profile?{...s.profile,...safe}:null}));notify('Profile updated')})},
 follow:name=>{if(!guard())return;setW(s=>({...s,following:s.following.includes(name)?s.following.filter(x=>x!==name):[...s.following,name]}))},
 logout:async()=>{if(!demo&&supabase)await supabase.auth.signOut();setW({...seed(),profile:null,saved:[],liked:[],conversations:[],notifications:[]});setDemo(true);setAdminPreview(false);notify('You’ve been signed out.')},
 enterDemo:()=>{setDemo(true);setW(seed());setAdminPreview(false);notify('Welcome to your private demo workspace.')},addNotice};
 return <Context.Provider value={value}>{children}</Context.Provider>
}
export const useStore=()=>useContext(Context);
