import React,{useRef,useState} from 'react';
import {FlatList,Linking,Modal,Pressable,View,useWindowDimensions} from 'react-native';
import {Image} from 'expo-image';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useTheme} from '../lib/theme';
import {useStore} from '../lib/store';
import {useUI} from '../lib/navigation';
import {imageSource,money} from '../lib/data';
import {Avatar,Badge,Button,Card,Empty,Icon,IconButton,ModalFrame,NoticeBox,Row,T} from '../components/ui';
export default function Details({id}:{id:string}){const{c}=useTheme();const s=useStore();const ui=useUI();const p=s.properties.find(p=>p.id===id);const[index,setIndex]=useState(0);const{width}=useWindowDimensions();if(!p)return <ModalFrame title="Property unavailable" onClose={ui.close}><Empty title="This chapter has closed" body="This property may have been removed by its owner."/></ModalFrame>;const saved=s.saved.includes(id);return <ModalFrame wide title="A closer look" subtitle={`${p.type} · ${p.locality}, ${p.city}`} onClose={ui.close} footer={<Row style={{justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><View><T size={23} weight="extra" color={c.navy}>{money(p.price)}{p.purpose==='Rent'&&<T size={11}> / month</T>}</T><T size={10} color={c.muted}>{p.purpose==='Sale'?'Your next chapter starts here':'A space to make your own'}</T></View><Row style={{gap:9,flexWrap:'wrap',maxWidth:'100%'}}><Button title="Chat with seller" variant="outline" icon="chatbubbles-outline" onPress={()=>ui.chat(p)}/><Button title="Book property" icon="wallet-outline" onPress={()=>ui.open('payment',p.id)} disabled={!['For Sale','For Rent'].includes(p.status)}/></Row></Row>}>
 <View style={{borderRadius:12,overflow:'hidden'}}><Pressable onPress={()=>ui.open('gallery',{id,index})}><Image source={imageSource(p.photos[index])} style={{width:'100%',height:width<700?260:380}} contentFit="cover" priority="high" transition={0}/></Pressable><View style={{position:'absolute',top:14,left:14}}><Badge bg="#fff" color="#26785C">{p.status}</Badge></View><IconButton name="expand-outline" label="Full-screen gallery" onPress={()=>ui.open('gallery',{id,index})} color="#fff" style={{position:'absolute',right:15,bottom:15,backgroundColor:'#1C254BAA'}}/>{p.photos.length>1&&<><IconButton name="chevron-back" label="Previous photo" onPress={()=>setIndex((index+p.photos.length-1)%p.photos.length)} color="#fff" style={{position:'absolute',left:12,top:'45%',backgroundColor:'#1C254BAA'}}/><IconButton name="chevron-forward" label="Next photo" onPress={()=>setIndex((index+1)%p.photos.length)} color="#fff" style={{position:'absolute',right:12,top:'45%',backgroundColor:'#1C254BAA'}}/></>}</View>
 <FlatList horizontal data={p.photos} keyExtractor={(_,i)=>String(i)} showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:9}} renderItem={({item,index:i})=><Pressable onPress={()=>setIndex(i)} accessibilityLabel={`View photo ${i+1}`} style={{borderWidth:2,borderColor:i===index?c.primary:'transparent',padding:2,borderRadius:8}}><Image source={imageSource(item)} style={{width:85,height:58,borderRadius:5}} contentFit="cover"/></Pressable>}/>
 <Row style={{justifyContent:'space-between',alignItems:'flex-start',gap:12}}><View style={{flex:1}}><T size={24} weight="extra" style={{letterSpacing:-.7}}>{p.beds>0?`${p.beds} BHK `:''}{p.type} in {p.locality}</T><Row style={{gap:5,marginTop:7}}><Icon name="location-outline" size={16}/><T size={12} color={c.muted} style={{flex:1}}>{p.address}, {p.locality}, {p.city}, {p.state} {p.pin}</T></Row></View><IconButton name={saved?'bookmark':'bookmark-outline'} label={saved?'Unsave':'Save property'} color={c.primary} onPress={()=>s.toggleSave(p.id)}/><IconButton name="share-social-outline" label="Share property" onPress={()=>ui.open('share',p.id)}/></Row>
 {p.demo&&<NoticeBox>Sample listing · Images, address, seller, and price are illustrative. No real booking or seller contact is available for this demo property.</NoticeBox>}
 <Row style={{flexWrap:'wrap',backgroundColor:c.input,borderRadius:11,padding:18,gap:25}}>{[['expand-outline',`${p.area.toLocaleString()} sq ft`,'Built-up area'],['bed-outline',String(p.beds),'Bedrooms'],['water-outline',String(p.baths),'Bathrooms'],['car-outline',String(p.parking),'Parking spaces']].map(([icon,value,label])=><View key={label} style={{flex:1,minWidth:100,gap:4}}><Icon name={icon} size={21} color={c.primary}/><T size={15} weight="bold">{value}</T><T size={10} color={c.muted}>{label}</T></View>)}</Row>
 <View style={{gap:9}}><T size={17} weight="bold">A home with a little more heart</T><T size={13} color={c.muted} style={{lineHeight:23}}>{p.description}</T></View>
 <T size={17} weight="bold">The details that matter</T><Row style={{flexWrap:'wrap',gap:22}}>{[['Property type',p.type],['Listing type',p.purpose==='Sale'?'For sale':'For rent'],['Furnishing',p.furnishing],['Floor',`${p.floor} of ${p.floors}`],['Property age',p.age],['Availability',p.available],['Verification',p.verified?'Verified':'Not yet verified'],['Listing ID',p.id]].map(([label,value])=><View key={label} style={{width:width<600?'44%':'22%',gap:3}}><T size={10} color={c.muted}>{label}</T><T size={12} weight="semi">{value}</T></View>)}</Row>
 <T size={17} weight="bold">Comforts, included</T><Row style={{flexWrap:'wrap',gap:10}}>{p.amenities.map(a=><Row key={a} style={{gap:6,padding:10,paddingHorizontal:13,backgroundColor:c.input,borderRadius:7}}><Icon name="checkmark-circle-outline" size={15} color={c.green}/><T size={11}>{a}</T></Row>)}</Row>
 <Card style={{padding:19,backgroundColor:c.input}}><Row style={{gap:14}}><View style={{width:49,height:49,borderRadius:13,backgroundColor:c.tint,alignItems:'center',justifyContent:'center'}}><Icon name="map-outline" size={26} color={c.primary}/></View><View style={{flex:1}}><T size={14} weight="bold">Get to know {p.locality}</T><T size={11} color={c.muted}>{p.city}, {p.state} · Approximate neighborhood</T></View><Button title="Open map" small variant="outline" onPress={()=>Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.locality+', '+p.city+', '+p.state)}`).catch(()=>s.notify('Maps could not be opened on this device.'))}/></Row></Card>
 <Card style={{padding:18}}><Row style={{gap:13}}><Avatar source={p.sellerPhoto} size={49}/><View style={{flex:1}}><Pressable onPress={()=>ui.open('seller',p.ownerId)}><T size={14} weight="bold">{p.seller}</T></Pressable><T size={11} color={c.muted}>{p.sellerRole} · {p.city}</T></View><Button title="View profile" variant="outline" small onPress={()=>ui.open('seller',p.ownerId)}/></Row><Row style={{gap:10,marginTop:16}}><Button title="Contact seller" icon="call-outline" variant="outline" style={{flex:1}} onPress={()=>p.phone?Linking.openURL(`tel:${p.phone}`).catch(()=>s.notify('Calling is not supported on this device.')):s.notify('Contact details are private for demo sellers. Try a demo conversation instead.')}/><Button title="Start a conversation" icon="chatbubble-ellipses-outline" style={{flex:1}} onPress={()=>ui.chat(p)}/></Row></Card>
 <Pressable onPress={()=>ui.open('report',p.id)} style={{alignSelf:'center',flexDirection:'row',gap:6,alignItems:'center'}}><Icon name="flag-outline" size={13}/><T size={11} color={c.muted}>Something doesn’t look right? Report this property</T></Pressable>
 </ModalFrame>}
export function Gallery({id,index=0}:any){const s=useStore();const ui=useUI();const p=s.properties.find(p=>p.id===id);const{width,height}=useWindowDimensions();const[current,setCurrent]=useState(index);const ref=useRef<FlatList>(null);if(!p||!p.photos.length)return <ModalFrame title="No photos yet" onClose={ui.close}><Empty icon="images-outline" title="Give this place a little perspective" body="Add property photos to preview the full-screen gallery."/></ModalFrame>;const move=(i:number)=>{const n=(i+p.photos.length)%p.photos.length;ref.current?.scrollToIndex({index:n,animated:true});setCurrent(n)};return <Modal visible animationType="fade" onRequestClose={ui.close}><SafeAreaView style={{flex:1,backgroundColor:'#111729'}}><Row style={{justifyContent:'space-between',padding:20}}><View><T size={16} color="#fff" weight="bold">{p.beds} BHK {p.type} · {p.locality}</T><T size={11} color="#B6BCD0">{current+1} of {p.photos.length} photos</T></View><IconButton name="close" label="Close gallery" color="#fff" onPress={ui.close}/></Row><View style={{flex:1,justifyContent:'center'}}><FlatList ref={ref} data={p.photos} horizontal pagingEnabled initialScrollIndex={index} getItemLayout={(_,i)=>({length:width,offset:width*i,index:i})} showsHorizontalScrollIndicator={false} onMomentumScrollEnd={e=>setCurrent(Math.round(e.nativeEvent.contentOffset.x/width))} keyExtractor={(_,i)=>String(i)} renderItem={({item})=><Image source={imageSource(item)} style={{width,height:height-210}} contentFit="contain"/>}/><IconButton name="chevron-back" label="Previous image" color="#fff" onPress={()=>move(current-1)} style={{position:'absolute',left:20,backgroundColor:'#FFFFFF22',width:44,height:44}}/><IconButton name="chevron-forward" label="Next image" color="#fff" onPress={()=>move(current+1)} style={{position:'absolute',right:20,backgroundColor:'#FFFFFF22',width:44,height:44}}/></View><Row style={{justifyContent:'center',gap:9,padding:20}}>{p.photos.map((photo,i)=><Pressable key={i} onPress={()=>move(i)} style={{borderWidth:2,borderColor:i===current?'#A2AAFF':'transparent',padding:2,borderRadius:6}}><Image source={imageSource(photo)} style={{width:60,height:44,borderRadius:3}} contentFit="cover"/></Pressable>)}</Row></SafeAreaView></Modal>}
