import React,{useMemo,useState} from 'react';
import {FlatList,Pressable,RefreshControl,View,useWindowDimensions} from 'react-native';
import {Image} from 'expo-image';
import {LinearGradient} from 'expo-linear-gradient';
import Animated,{FadeIn} from 'react-native-reanimated';
import {useTheme} from '../lib/theme';
import {useStore} from '../lib/store';
import {useUI} from '../lib/navigation';
import {photos} from '../lib/data';
import {Card,Empty,Icon,IconButton,Row,Skeleton,T} from '../components/ui';
import PropertyCard from '../components/PropertyCard';
export default function Feed(){const{width}=useWindowDimensions();const compact=width<550;const{c}=useTheme();const s=useStore();const ui=useUI();const[tab,setTab]=useState('For you');const[purpose,setPurpose]=useState('Buy');const[location,setLocation]=useState('Bhopal');const[type,setType]=useState('All properties');const data=useMemo(()=>{let list=s.properties.filter(p=>['For Sale','For Rent'].includes(p.status));if(tab==='Featured')list=list.filter(p=>p.featured);if(tab==='Nearby')list=list.filter(p=>p.city===(s.profile?.city.split(',')[0]||'Bhopal'));if(tab==='Recently viewed')list=s.recent.map(id=>list.find(p=>p.id===id)).filter(Boolean) as typeof list;if(tab==='Latest')list.sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt));return list},[s.properties,tab,s.recent]);
 return <FlatList data={s.loading?[]:data} keyExtractor={p=>p.id} renderItem={({item})=><PropertyCard property={item}/>} showsVerticalScrollIndicator={false} contentContainerStyle={{paddingBottom:35}} refreshControl={<RefreshControl refreshing={s.loading} onRefresh={s.refresh} tintColor={c.primary}/>} ListHeaderComponent={<View>
 <Animated.View entering={FadeIn.duration(400)}><Pressable onPress={()=>ui.navigate('Explore')} accessibilityLabel="Explore your next home"><Card style={{height:148,backgroundColor:'#EAEDF8',borderColor:'#E5E9F6',marginBottom:18}}><Image source={photos.house} style={{position:'absolute',right:0,width:'59%',height:'100%'}} contentFit="cover" contentPosition="right center"/><LinearGradient colors={['#EDF0FA','#EDF0FAF5','#EDF0FA12']} locations={[0,.43,1]} start={{x:0,y:0}} end={{x:1,y:0}} style={{position:'absolute',inset:0} as any}/><View style={{padding:23,paddingTop:20}}><T size={8} weight="extra" color="#65709E" style={{letterSpacing:1.9,marginBottom:7}}>SPACES FOR EVERY STORY</T><T size={compact?(width<360?20:23):26} weight="extra" color="#27315C" style={{lineHeight:33,letterSpacing:-.8}}>Find a place.{'\n'}Start your next chapter.</T><Row style={{gap:7,marginTop:8}}><T size={10} color="#697493">Buy. Rent. Belong.</T><Icon name="arrow-forward" size={13} color="#6774AD"/></Row></View></Card></Pressable></Animated.View>
 <Card style={{padding:11,marginBottom:23}}><Row style={{gap:10}}><Row style={{padding:3,backgroundColor:c.input,borderRadius:7}}>{['Buy','Rent'].map(p=><Pressable key={p} onPress={()=>setPurpose(p)} style={{paddingHorizontal:13,paddingVertical:9,borderRadius:5,backgroundColor:purpose===p?c.card:'transparent',shadowColor:'#1e2350',shadowOpacity:purpose===p?.06:0,shadowRadius:4}}><T size={11} weight="bold" color={purpose===p?c.primary:c.muted}>{p}</T></Pressable>)}</Row><View style={{width:1,height:27,backgroundColor:c.line}}/><Pressable onPress={()=>setLocation(l=>l==='Bhopal'?'Indore':l==='Indore'?'All locations':'Bhopal')} style={{flex:1,flexDirection:'row',alignItems:'center',gap:6}}><Icon name="location-outline" size={15}/><View style={{flex:1}}><T size={8} color={c.muted} numberOfLines={1}>Location</T><T size={11} weight="semi" numberOfLines={1}>{location}</T></View><Icon name="chevron-down" size={11}/></Pressable>{!compact&&<><View style={{width:1,height:27,backgroundColor:c.line}}/><Pressable onPress={()=>setType(t=>t==='All properties'?'Apartment':t==='Apartment'?'Villa':'All properties')} style={{flex:1,flexDirection:'row',alignItems:'center',gap:6}}><View style={{flex:1}}><T size={8} color={c.muted}>Property type</T><T size={11} weight="semi" numberOfLines={1}>{type}</T></View><Icon name="chevron-down" size={11}/></Pressable></>}<IconButton name="search" label="Search properties" color="#fff" style={{backgroundColor:c.primary,width:39,height:39,borderRadius:8}} onPress={()=>{ui.setQuery(location==='All locations'?'':location);ui.navigate('Explore',{purpose:purpose==='Buy'?'Sale':'Rent',type:type==='All properties'?'All types':type})}}/></Row></Card>
 <Row style={{justifyContent:'space-between',marginBottom:15,alignItems:'flex-end'}}><Row style={{gap:17,flexWrap:'wrap',flex:1}}>{['For you','Latest','Nearby','Featured'].map(t=><Pressable key={t} onPress={()=>setTab(t)} accessibilityRole="tab" accessibilityState={{selected:tab===t}} style={{paddingBottom:11,borderBottomWidth:2,borderColor:tab===t?c.primary:'transparent'}}><T size={11} weight={tab===t?'bold':'medium'} color={tab===t?c.primary:c.muted}>{t==='For you'?'Recommended':t}</T></Pressable>)}</Row><Pressable onPress={()=>setTab(tab==='Recently viewed'?'For you':'Recently viewed')} accessibilityLabel="Recently viewed properties" style={{paddingBottom:11,flexDirection:'row',alignItems:'center',gap:5}}><Icon name="time-outline" size={13} color={tab==='Recently viewed'?c.primary:c.muted}/><T size={9} color={c.muted}>Recent</T></Pressable></Row>
 </View>} ListEmptyComponent={s.loading?<Skeleton/>:s.error?<Empty title="Let’s try that again" body={s.error} action="Retry" onAction={s.refresh}/>:<Empty icon="home-outline" title={tab==='Recently viewed'?'Your journey starts here':'No places here just yet'} body={tab==='Recently viewed'?'Open a property to add it to your recently viewed collection.':'Try a different collection or explore all properties.'} action="Explore properties" onAction={()=>ui.navigate('Explore')}/>}/>
}
